In [1]:
import polars as pl
import re
import pathlib
import requests
import typing, gzip, os
from requests.adapters import HTTPAdapter, Retry
retries = Retry(total=5, backoff_factor=0.25, status_forcelist=[500, 502, 503, 504])
session = requests.Session()
session.mount("https://", HTTPAdapter(max_retries=retries))

In [2]:
CODON_MAP = {
    'TTT': 'F', 'TTC': 'F', 'TTA': 'L', 'TTG': 'L', 
    'TCT': 'S', 'TCC': 'S', 'TCA': 'S', 'TCG': 'S', 
    'TAT': 'Y', 'TAC': 'Y', 'TGT': 'C', 'TGC': 'C', 
    'TGG': 'W', 'CTT': 'L', 'CTC': 'L', 'CTA': 'L', 
    'CTG': 'L', 'CCT': 'P', 'CCC': 'P', 'CCA': 'P', 
    'CCG': 'P', 'CAT': 'H', 'CAC': 'H', 'CAA': 'Q', 
    'CAG': 'Q', 'CGT': 'R', 'CGC': 'R', 'CGA': 'R', 
    'CGG': 'R', 'ATT': 'I', 'ATC': 'I', 'ATA': 'I', 
    'ATG': 'M', 'ACT': 'T', 'ACC': 'T', 'ACA': 'T', 
    'ACG': 'T', 'AAT': 'N', 'AAC': 'N', 'AAA': 'K', 
    'AAG': 'K', 'AGT': 'S', 'AGC': 'S', 'AGA': 'R', 
    'AGG': 'R', 'GTT': 'V', 'GTC': 'V', 'GTA': 'V', 
    'GTG': 'V', 'GCT': 'A', 'GCC': 'A', 'GCA': 'A', 
    'GCG': 'A', 'GAT': 'D', 'GAC': 'D', 'GAA': 'E', 
    'GAG': 'E', 'GGT': 'G', 'GGC': 'G', 'GGA': 'G', 
    'GGG': 'G',
    'TAA': '*', 'TAG': '*', 'TGA': '*'
}

SGC_STOCKHOLM_SRC_COLUMNS = {
    'Construct ID': 'construct_id',
    'DNA Sequence': 'dna_seq',
    'Expression ID': 'expression_id',
    'Insoluble': 'insoluble',
    'Soluble': 'soluble',
    'Yield': 'yield_cat',
    'Comments': 'comments',
    'Record Creator': 'record_creator'
}

def pl_expr_seq_translate(col_expr:pl.Expr)->pl.Expr:
    return (
        col_expr.str.to_uppercase()
        .str.extract_all(r'(.{3})')
        .list.eval(pl.element().replace_strict(CODON_MAP, default='X'))
        .list.join('')
    )

In [3]:
df = pl.read_parquet("~/data/pp/ai/datasets/17_01/full.pqt").filter(source='SGC_Stockholm', unique_target_count=1)
alignments_df = pl.read_csv('~/data/pp/ai/datasets/17_01/full_alignments.csv.gz')
sgc_stockholm_df = pl.read_parquet('~/data/pp/ai/datasets/17_01/sgc-stockholm/sgc_stockholm.pqt')
sgc_stockholm_src_df = pl.read_csv('~/data/pp/ai/datasets/17_01/sgc-stockholm/sgc_stockholm_source.csv.gz')
uniprot_localisation_df_file = pathlib.Path('~/Documents/nicola_paper_2026/sgc_stockholm_expert_uniprot.parquet').expanduser()
# df = df.join(sgc_stockholm_df.select('id', 'yield_cat', 'insoluble', 'soluble'), on='id', how='inner')

In [4]:
# https://www.ncbi.nlm.nih.gov/nuccore/EF198106.1
pNic28_BSA4_seq="""
TAATACGACTCACTATAGGGGAATTGTGAGCGGATAACAATTCCCCTCTAGAAATAATTTTGTTTAACTT
TAAGAAGGAGATATACATATGCACCATCATCATCATCATTCTTCTGGTGTAGATCTGGGTACCGAGAACC
TGTACTTCCAATCCATGGAGACCGACGTCCACATATACCTGCCGTTCACTATTATTTAGTGAAATGAGAT
ATTATGATATTTTCTGAATTGTGATTAAAAAGGCAACTTTATGCCCATGCAACAGAAACTATAAAAAATA
CAGAGAATGAAAAGAAACAGATAGATTTTTTAGTTCTTTAGGCCCGTAGTCTGCAAATCCTTTTATGATT
TTCTATCAAACAAAAGAGGAAAATAGACCAGTTGCAATCCAAACGAGAGTCTAATAGAATGAGGTCGAAA
AGTAAATCGCGCGGGTTTGTTACTGATAAAGCAGGCAAGACCTAAAATGTGTAAAGGGCAAAGTGTATAC
TTTGGCGTCACCCCTTACATATTTTAGGTCTTTTTTTATTGTGCGTAACTAACTTGCCATCTTCAAACAG
GAGGGCTGGAAGAAGCAGACCGCTAACACAGTACATAAAAAAGGAGACATGAACGATGAACATCAAAAAG
TTTGCAAAACAAGCAACAGTATTAACCTTTACTACCGCACTGCTGGCAGGAGGCGCAACTCAAGCGTTTG
CGAAAGAAACGAACCAAAAGCCATATAAGGAAACATACGGCATTTCCCATATTACACGCCATGATATGCT
GCAAATCCCTGAACAGCAAAAAAATGAAAAATATAAAGTTCCTGAGTTCGATTCGTCCACAATTAAAAAT
ATCTCTTCTGCAAAAGGCCTGGACGTTTGGGACAGCTGGCCATTACAAAACACTGACGGCACTGTCGCAA
ACTATCACGGCTACCACATCGTCTTTGCATTAGCCGGAGATCCTAAAAATGCGGATGACACATCGATTTA
CATGTTCTATCAAAAAGTCGGCGAAACTTCTATTGACAGCTGGAAAAACGCTGGCCGCGTCTTTAAAGAC
AGCGACAAATTCGATGCAAATGATTCTATCCTAAAAGACCAAACACAAGAATGGTCAGGTTCAGCCACAT
TTACATCTGACGGAAAAATCCGTTTATTCTACACTGATTTCTCCGGTAAACATTACGGCAAACAAACACT
GACAACTGCACAAGTTAACGTATCAGCATCAGACAGCTCTTTGAACATCAACGGTGTAGAGGATTATAAA
TCAATCTTTGACGGTGACGGAAAAACGTATCAAAATGTACAGCAGTTCATCGATGAAGGCAACTACAGCT
CAGGCGACAACCATACGCTGAGAGATCCTCACTACGTAGAAGATAAAGGCCACAAATACTTAGTATTTGA
AGCAAACACTGGAACTGAAGATGGCTACCAAGGCGAAGAATCTTTATTTAACAAAGCATACTATGGCAAA
AGCACATCATTCTTCCGTCAAGAAAGTCAAAAACTTCTGCAAAGCGATAAAAAACGCACGGCTGAGTTAG
CAAACGGCGCTCTCGGTATGATTGAGCTAAACGATGATTACACACTGAAAAAAGTGATGAAACCGCTGAT
TGCATCTAACACAGTAACAGATGAAATTGAACGCGCGAACGTCTTTAAAATGAACGGCAAATGGTACCTG
TTCACTGACTCCCGCGGATCAAAAATGACGATTGACGGCATTACGTCTAACGATATTTACATGCTTGGTT
ATGTTTCTAATTCTTTAACTGGCCCATACAAGCCGCTGAACAAAACTGGCCTTGTGTTAAAAATGGATCT
TGATCCTAACGATGTAACCTTTACTTACTCACACTTCGCTGTACCTCAAGCGAAAGGAAACAATGTCGTG
ATTACAAGCTATATGACAAACAGAGGATTCTACGCAGACAAACAATCAACGTTTGCGCCTAGCTTCCTGC
TGAACATCAAAGGCAAGAAAACATCTGTTGTCAAAGACAGCATCCTTGAACAAGGACAATTAACAGTTAA
CAAATAAAAACGCAAAAGAAAATGCCGATATCCTATTGGCATTGACGGTCTCCAGTAAAGGTGGATACGG
ATCCGAATTCGAGCTCCGTCGACAAGCTTGCGGCCGCACTCGAGCACCACCACCACCACCACTGAGATCC
GGCTGCTAACAAAGCCCGAAAGGAAGCTGAGTTGGCTGCTGCCACCGCTGAGCAATAACTAGCATAACCC
CTTGGGGCCTCTAAACGGGTCTTGAGGGGTTTTTTGCTGAAAGGAGGAACTATATCCGGATTGGCGAATG
GGACGCGCCCTGTAGCGGCGCATTAAGCGCGGCGGGTGTGGTGGTTACGCGCAGCGTGACCGCTACACTT
GCCAGCGCCCTAGCGCCCGCTCCTTTCGCTTTCTTCCCTTCCTTTCTCGCCACGTTCGCCGGCTTTCCCC
GTCAAGCTCTAAATCGGGGGCTCCCTTTAGGGTTCCGATTTAGTGCTTTACGGCACCTCGACCCCAAAAA
ACTTGATTAGGGTGATGGTTCACGTAGTGGGCCATCGCCCTGATAGACGGTTTTTCGCCCTTTGACGTTG
GAGTCCACGTTCTTTAATAGTGGACTCTTGTTCCAAACTGGAACAACACTCAACCCTATCTCGGTCTATT
CTTTTGATTTATAAGGGATTTTGCCGATTTCGGCCTATTGGTTAAAAAATGAGCTGATTTAACAAAAATT
TAACGCGAATTTTAACAAAATATTAACGTTTACAATTTCAGGTGGCACTTTTCGGGGAAATGTGCGCGGA
ACCCCTATTTGTTTATTTTTCTAAATACATTCAAATATGTATCCGCTCATGAATTAATTCTTAGAAAAAC
TCATCGAGCATCAAATGAAACTGCAATTTATTCATATCAGGATTATCAATACCATATTTTTGAAAAAGCC
GTTTCTGTAATGAAGGAGAAAACTCACCGAGGCAGTTCCATAGGATGGCAAGATCCTGGTATCGGTCTGC
GATTCCGACTCGTCCAACATCAATACAACCTATTAATTTCCCCTCGTCAAAAATAAGGTTATCAAGTGAG
AAATCACCATGAGTGACGACTGAATCCGGTGAGAATGGCAAAAGTTTATGCATTTCTTTCCAGACTTGTT
CAACAGGCCAGCCATTACGCTCGTCATCAAAATCACTCGCATCAACCAAACCGTTATTCATTCGTGATTG
CGCCTGAGCGAGACGAAATACGCGATCGCTGTTAAAAGGACAATTACAAACAGGAATCGAATGCAACCGG
CGCAGGAACACTGCCAGCGCATCAACAATATTTTCACCTGAATCAGGATATTCTTCTAATACCTGGAATG
CTGTTTTCCCGGGGATCGCAGTGGTGAGTAACCATGCATCATCAGGAGTACGGATAAAATGCTTGATGGT
CGGAAGAGGCATAAATTCCGTCAGCCAGTTTAGTCTGACCATCTCATCTGTAACATCATTGGCAACGCTA
CCTTTGCCATGTTTCAGAAACAACTCTGGCGCATCGGGCTTCCCATACAATCGATAGATTGTCGCACCTG
ATTGCCCGACATTATCGCGAGCCCATTTATACCCATATAAATCAGCATCCATGTTGGAATTTAATCGCGG
CCTAGAGCAAGACGTTTCCCGTTGAATATGGCTCATAACACCCCTTGTATTACTGTTTATGTAAGCAGAC
AGTTTTATTGTTCATGACCAAAATCCCTTAACGTGAGTTTTCGTTCCACTGAGCGTCAGACCCCGTAGAA
AAGATCAAAGGATCTTCTTGAGATCCTTTTTTTCTGCGCGTAATCTGCTGCTTGCAAACAAAAAAACCAC
CGCTACCAGCGGTGGTTTGTTTGCCGGATCAAGAGCTACCAACTCTTTTTCCGAAGGTAACTGGCTTCAG
CAGAGCGCAGATACCAAATACTGTCCTTCTAGTGTAGCCGTAGTTAGGCCACCACTTCAAGAACTCTGTA
GCACCGCCTACATACCTCGCTCTGCTAATCCTGTTACCAGTGGCTGCTGCCAGTGGCGATAAGTCGTGTC
TTACCGGGTTGGACTCAAGACGATAGTTACCGGATAAGGCGCAGCGGTCGGGCTGAACGGGGGGTTCGTG
CACACAGCCCAGCTTGGAGCGAACGACCTACACCGAACTGAGATACCTACAGCGTGAGCTATGAGAAAGC
GCCACGCTTCCCGAAGGGAGAAAGGCGGACAGGTATCCGGTAAGCGGCAGGGTCGGAACAGGAGAGCGCA
CGAGGGAGCTTCCAGGGGGAAACGCCTGGTATCTTTATAGTCCTGTCGGGTTTCGCCACCTCTGACTTGA
GCGTCGATTTTTGTGATGCTCGTCAGGGGGGCGGAGCCTATGGAAAAACGCCAGCAACGCGGCCTTTTTA
CGGTTCCTGGCCTTTTGCTGGCCTTTTGCTCACATGTTCTTTCCTGCGTTATCCCCTGATTCTGTGGATA
ACCGTATTACCGCCTTTGAGTGAGCTGATACCGCTCGCCGCAGCCGAACGACCGAGCGCAGCGAGTCAGT
GAGCGAGGAAGCGGAAGAGCGCCTGATGCGGTATTTTCTCCTTACGCATCTGTGCGGTATTTCACACCGC
ATATATGGTGCACTCTCAGTACAATCTGCTCTGATGCCGCATAGTTAAGCCAGTATACACTCCGCTATCG
CTACGTGACTGGGTCATGGCTGCGCCCCGACACCCGCCAACACCCGCTGACGCGCCCTGACGGGCTTGTC
TGCTCCCGGCATCCGCTTACAGACAAGCTGTGACCGTCTCCGGGAGCTGCATGTGTCAGAGGTTTTCACC
GTCATCACCGAAACGCGCGAGGCAGCTGCGGTAAAGCTCATCAGCGTGGTCGTGAAGCGATTCACAGATG
TCTGCCTGTTCATCCGCGTCCAGCTCGTTGAGTTTCTCCAGAAGCGTTAATGTCTGGCTTCTGATAAAGC
GGGCCATGTTAAGGGCGGTTTTTTCCTGTTTGGTCACTGATGCCTCCGTGTAAGGGGGATTTCTGTTCAT
GGGGGTAATGATACCGATGAAACGAGAGAGGATGCTCACGATACGGGTTACTGATGATGAACATGCCCGG
TTACTGGAACGTTGTGAGGGTAAACAACTGGCGGTATGGATGCGGCGGGACCAGAGAAAAATCACTCAGG
GTCAATGCCAGCGCTTCGTTAATACAGATGTAGGTGTTCCACAGGGTAGCCAGCAGCATCCTGCGATGCA
GATCCGGAACATAATGGTGCAGGGCGCTGACTTCCGCGTTTCCAGACTTTACGAAACACGGAAACCGAAG
ACCATTCATGTTGTTGCTCAGGTCGCAGACGTTTTGCAGCAGCAGTCGCTTCACGTTCGCTCGCGTATCG
GTGATTCATTCTGCTAACCAGTAAGGCAACCCCGCCAGCCTAGCCGGGTCCTCAACGACAGGAGCACGAT
CATGCGCACCCGTGGGGCCGCCATGCCGGCGATAATGGCCTGCTTCTCGCCGAAACGTTTGGTGGCGGGA
CCAGTGACGAAGGCTTGAGCGAGGGCGTGCAAGATTCCGAATACCGCAAGCGACAGGCCGATCATCGTCG
CGCTCCAGCGAAAGCGGTCCTCGCCGAAAATGACCCAGAGCGCTGCCGGCACCTGTCCTACGAGTTGCAT
GATAAAGAAGACAGTCATAAGTGCGGCGACGATAGTCATGCCCCGCGCCCACCGGAAGGAGCTGACTGGG
TTGAAGGCTCTCAAGGGCATCGGTCGAGATCCCGGTGCCTAATGAGTGAGCTAACTTACATTAATTGCGT
TGCGCTCACTGCCCGCTTTCCAGTCGGGAAACCTGTCGTGCCAGCTGCATTAATGAATCGGCCAACGCGC
GGGGAGAGGCGGTTTGCGTATTGGGCGCCAGGGTGGTTTTTCTTTTCACCAGTGAGACGGGCAACAGCTG
ATTGCCCTTCACCGCCTGGCCCTGAGAGAGTTGCAGCAAGCGGTCCACGCTGGTTTGCCCCAGCAGGCGA
AAATCCTGTTTGATGGTGGTTAACGGCGGGATATAACATGAGCTGTCTTCGGTATCGTCGTATCCCACTA
CCGAGATATCCGCACCAACGCGCAGCCCGGACTCGGTAATGGCGCGCATTGCGCCCAGCGCCATCTGATC
GTTGGCAACCAGCATCGCAGTGGGAACGATGCCCTCATTCAGCATTTGCATGGTTTGTTGAAAACCGGAC
ATGGCACTCCAGTCGCCTTCCCGTTCCGCTATCGGCTGAATTTGATTGCGAGTGAGATATTTATGCCAGC
CAGCCAGACGCAGACGCGCCGAGACAGAACTTAATGGGCCCGCTAACAGCGCGATTTGCTGGTGACCCAA
TGCGACCAGATGCTCCACGCCCAGTCGCGTACCGTCTTCATGGGAGAAAATAATACTGTTGATGGGTGTC
TGGTCAGAGACATCAAGAAATAACGCCGGAACATTAGTGCAGGCAGCTTCCACAGCAATGGCATCCTGGT
CATCCAGCGGATAGTTAATGATCAGCCCACTGACGCGTTGCGCGAGAAGATTGTGCACCGCCGCTTTACA
GGCTTCGACGCCGCTTCGTTCTACCATCGACACCACCACGCTGGCACCCAGTTGATCGGCGCGAGATTTA
ATCGCCGCGACAATTTGCGACGGCGCGTGCAGGGCCAGACTGGAGGTGGCAACGCCAATCAGCAACGACT
GTTTGCCCGCCAGTTGTTGTGCCACGCGGTTGGGAATGTAATTCAGCTCCGCCATCGCCGCTTCCACTTT
TTCCCGCGTTTTCGCAGAAACGTGGCTGGCCTGGTTCACCACGCGGGAAACGGTCTGATAAGAGACACCG
GCATACTCTGCGACATCGTATAACGTTACTGGTTTCACATTCACCACCCTGAATTGACTCTCTTCCGGGC
GCTATCATGCCATACCGCGAAAGGTTTTGCGCCATTCGATGGTGTCCGGGATCTCGACGCTCTCCCTTAT
GCGACTCCTGCATTAGGAAGCAGCCCAGTAGTAGGTTGAGGCCGTTGAGCACCGCCGCCGCAAGGAATGG
TGCATGCAAGGAGATGGCGCCCAACAGTCCCCCGGCCACGGGGCCTGCCACCATACCCACGCCGAAACAA
GCGCTCATGAGCCCGAAGTGGCGAGCCCGATCTTCCCCATCGGTGATGTCGGCGATATAGGCGCCAGCAA
CCGCACCTGTGGCGCCGGTGATGCCGGCCACGATGCGTCCGGCGTAGAGGATCGAGATCTCGATCCCGCG
AAAT"""
pNic28_BSA4_seq = re.compile(r'\s+').sub('', pNic28_BSA4_seq)
pNic28_BSA4_seq
# Email from Opher Gileadi
replace_BsaI='ATGCACCATCATCATCATCATTCTTCTGGTGTAGATCTGGGTACCGAGAACCTGTACTTCCAATCCATGGAGACCGACGTCCACATATACCTGCCGTTCACTATTATTTAGTGAAATGAGATATTATGATATTTTCTGAATTGTGATTAAAAAGGCAACTTTATGCCCATGCAACAGAAACTATAAAAAATACAGAGAATGAAAAGAAACAGATAGATTTTTTAGTTCTTTAGGCCCGTAGTCTGCAAATCCTTTTATGATTTTCTATCAAACAAAAGAGGAAAATAGACCAGTTGCAATCCAAACGAGAGTCTAATAGAATGAGGTCGAAAAGTAAATCGCGCGGGTTTGTTACTGATAAAGCAGGCAAGACCTAAAATGTGTAAAGGGCAAAGTGTATACTTTGGCGTCACCCCTTACATATTTTAGGTCTTTTTTTATTGTGCGTAACTAACTTGCCATCTTCAAACAGGAGGGCTGGAAGAAGCAGACCGCTAACACAGTACATAAAAAAGGAGACATGAACGATGAACATCAAAAAGTTTGCAAAACAAGCAACAGTATTAACCTTTACTACCGCACTGCTGGCAGGAGGCGCAACTCAAGCGTTTGCGAAAGAAACGAACCAAAAGCCATATAAGGAAACATACGGCATTTCCCATATTACACGCCATGATATGCTGCAAATCCCTGAACAGCAAAAAAATGAAAAATATAAAGTTCCTGAGTTCGATTCGTCCACAATTAAAAATATCTCTTCTGCAAAAGGCCTGGACGTTTGGGACAGCTGGCCATTACAAAACACTGACGGCACTGTCGCAAACTATCACGGCTACCACATCGTCTTTGCATTAGCCGGAGATCCTAAAAATGCGGATGACACATCGATTTACATGTTCTATCAAAAAGTCGGCGAAACTTCTATTGACAGCTGGAAAAACGCTGGCCGCGTCTTTAAAGACAGCGACAAATTCGATGCAAATGATTCTATCCTAAAAGACCAAACACAAGAATGGTCAGGTTCAGCCACATTTACATCTGACGGAAAAATCCGTTTATTCTACACTGATTTCTCCGGTAAACATTACGGCAAACAAACACTGACAACTGCACAAGTTAACGTATCAGCATCAGACAGCTCTTTGAACATCAACGGTGTAGAGGATTATAAATCAATCTTTGACGGTGACGGAAAAACGTATCAAAATGTACAGCAGTTCATCGATGAAGGCAACTACAGCTCAGGCGACAACCATACGCTGAGAGATCCTCACTACGTAGAAGATAAAGGCCACAAATACTTAGTATTTGAAGCAAACACTGGAACTGAAGATGGCTACCAAGGCGAAGAATCTTTATTTAACAAAGCATACTATGGCAAAAGCACATCATTCTTCCGTCAAGAAAGTCAAAAACTTCTGCAAAGCGATAAAAAACGCACGGCTGAGTTAGCAAACGGCGCTCTCGGTATGATTGAGCTAAACGATGATTACACACTGAAAAAAGTGATGAAACCGCTGATTGCATCTAACACAGTAACAGATGAAATTGAACGCGCGAACGTCTTTAAAATGAACGGCAAATGGTACCTGTTCACTGACTCCCGCGGATCAAAAATGACGATTGACGGCATTACGTCTAACGATATTTACATGCTTGGTTATGTTTCTAATTCTTTAACTGGCCCATACAAGCCGCTGAACAAAACTGGCCTTGTGTTAAAAATGGATCTTGATCCTAACGATGTAACCTTTACTTACTCACACTTCGCTGTACCTCAAGCGAAAGGAAACAATGTCGTGATTACAAGCTATATGACAAACAGAGGATTCTACGCAGACAAACAATCAACGTTTGCGCCTAGCTTCCTGCTGAACATCAAAGGCAAGAAAACATCTGTTGTCAAAGACAGCATCCTTGAACAAGGACAATTAACAGTTAACAAATAAAAACGCAAAAGAAAATGCCGATATCCTATTGGCATTGACGGTCTCC'

In [5]:
(pNic28_BSA4_seq.index(replace_BsaI), pNic28_BSA4_seq.index(replace_BsaI) + len(replace_BsaI))

(88, 2083)

In [6]:
sgc_stockholm_fixed_df = (
    sgc_stockholm_src_df
    .rename(SGC_STOCKHOLM_SRC_COLUMNS)
    .filter(pl.col.dna_seq.is_not_null(), pl.col.yield_cat.is_not_null())
    .with_columns(pl.col.dna_seq.str.slice(0, pl.col.dna_seq.str.len_bytes() // 3 * 3))
    .with_columns(protein_seq=pl_expr_seq_translate(pl.col.dna_seq))
    .with_columns(
        protein_seq_start=pl.when(
            pl.col.protein_seq.str.contains('^H+M') | 
            pl.col.protein_seq.str.starts_with('KRR*LM') | 
            pl.col.protein_seq.str.starts_with('LRRRYTM')
        ).then(pl.col.protein_seq.str.find('M')).otherwise(0),
    )
    .with_columns(
        dna_seq_start=pl.col.protein_seq_start * 3,
        protein_stop_codon_pos=pl.col.protein_seq_start + 
            pl.col.protein_seq.str.slice(pl.col.protein_seq_start).str.find('*', literal=True)
    )
    .with_columns(
        dna_seq_end=3 * (pl.col.protein_seq_start + pl.col.protein_stop_codon_pos + 
                    pl.col.protein_seq.str.slice(pl.col.protein_seq_start + pl.col.protein_stop_codon_pos).str.find('[^*]'))
    )
    .with_columns(dna_seq_fixed=pl.col.dna_seq.str.slice(pl.col.dna_seq_start, pl.col.dna_seq_end - pl.col.dna_seq_start))
    .filter(pl.col.dna_seq_fixed.str.starts_with('ATG'))
    .with_columns(protein_seq_translated=pl_expr_seq_translate(pl.col.dna_seq_fixed))
    .filter(pl.col.protein_seq_translated.str.slice(-1) == '*')
)
# check that dna sequence is unique per construct id
assert sgc_stockholm_fixed_df.group_by('construct_id').agg(pl.col.dna_seq_fixed.n_unique()).select((pl.col.dna_seq_fixed > 1).sum()).item() == 0
# check that ('construct_id', 'expression_id') id unique
assert sgc_stockholm_fixed_df.group_by('construct_id', 'expression_id').len().select((pl.col.len == 1).all()).item()
# check that protein sequences match
assert (df.select('id', 'protein_seq')
    .join(sgc_stockholm_df.select('id', 'construct_id', 'expression_id'), on='id', how='inner')
    .join(sgc_stockholm_fixed_df.select('construct_id',  'expression_id', 'protein_seq_translated'), on=('construct_id', 'expression_id'), how='inner')
    .select((pl.col.protein_seq.str.replace(r'\*+$', '') == pl.col.protein_seq).all())
    .item()
)
df = (
    df.select('id', 'fasta_id', 'dna_fasta_id', 'yield_binary', 'uniprot_id', 'taxon_id', 'gene_id')
    .with_columns(pl.col.gene_id.replace({'nan': None}), vector_seq=pl.lit(pNic28_BSA4_seq))
    .join(sgc_stockholm_df.select('id', 'construct_id', 'expression_id', 'yield_cat'), on='id', how='inner')
    .join(sgc_stockholm_fixed_df.select('construct_id',  'expression_id', 'protein_seq_translated', 'dna_seq_fixed'), on=('construct_id', 'expression_id'), how='inner')
    .rename({'protein_seq_translated': 'protein_seq', 'dna_seq_fixed': 'dna_seq'})
    .with_columns(
        pl.col.protein_seq.str.replace(r'\*+$', ''),
        pl.col.vector_seq.str.replace_all(pl.lit(replace_BsaI), pl.col.dna_seq, literal=True)
    )
    .sort('id')
)
df

shape: (14_676, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ fasta_id  ┆ dna_fasta ┆ yield_bin ┆ … ┆ expressio ┆ yield_cat ┆ protein_s ┆ dna_seq  │
│ ---       ┆ ---       ┆ _id       ┆ ary       ┆   ┆ n_id      ┆ ---       ┆ eq        ┆ ---      │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ i64       ┆ ---       ┆ str      │
│           ┆           ┆ str       ┆ bool      ┆   ┆ str       ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ SGC_S_000 ┆ SGC_S_000 ┆ SGC_S_000 ┆ true      ┆ … ┆ ARR3A-e01 ┆ 2         ┆ MHHHHHHSS ┆ ATGCACCA │
│ 000       ┆ 000       ┆ 000       ┆           ┆   ┆ 5         ┆           ┆ GVDLGTENL ┆ TCATCATC │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ YFQSMKVFK ┆ ATCATTCT │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ KTS…      ┆ TCTGGT…  │
│ SGC_S_000 ┆ SGC_S_000 ┆ SGC_S_000 ┆ true      ┆ … ┆ ARR3A-e01 ┆ 2         ┆ MHHHHHHSS ┆ ATGCACCA │
│ 001       ┆ 001       ┆ 001       ┆           ┆   ┆ 6         ┆           ┆ GVDLGTENL ┆ TCATCATC │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ YFQSMKVFK ┆ ATCATTCT │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ KTS…      ┆ TCTGGT…  │
│ SGC_S_000 ┆ SGC_S_000 ┆ SGC_S_000 ┆ true      ┆ … ┆ ARRDC3A-e ┆ 2         ┆ MHHHHHHSS ┆ ATGCACCA │
│ 002       ┆ 002       ┆ 002       ┆           ┆   ┆ 006       ┆           ┆ GVDLGTENL ┆ TCATCATC │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ YFQSMVLGK ┆ ATCATTCT │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ VKS…      ┆ TCTGGT…  │
│ SGC_S_000 ┆ SGC_S_000 ┆ SGC_S_000 ┆ true      ┆ … ┆ ARRDC3A-e ┆ 2         ┆ MHHHHHHSS ┆ ATGCACCA │
│ 003       ┆ 003       ┆ 003       ┆           ┆   ┆ 007       ┆           ┆ GVDLGTENL ┆ TCATCATC │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ YFQSMVLGK ┆ ATCATTCT │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ VKS…      ┆ TCTGGT…  │
│ SGC_S_000 ┆ SGC_S_000 ┆ SGC_S_000 ┆ false     ┆ … ┆ ARRDC3A-e ┆ 0         ┆ MHHHHHHSS ┆ ATGCACCA │
│ 004       ┆ 004       ┆ 004       ┆           ┆   ┆ 008       ┆           ┆ GVDLGTENL ┆ TCATCATC │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ YFQSMVLGK ┆ ATCATTCT │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ VKS…      ┆ TCTGGT…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ SGC_S_014 ┆ SGC_S_014 ┆ SGC_S_014 ┆ false     ┆ … ┆ SOCS7A-e0 ┆ 0         ┆ MHHHHHHHH ┆ ATGCACCA │
│ 986       ┆ 986       ┆ 986       ┆           ┆   ┆ 01        ┆           ┆ HHDLGTENL ┆ TCATCATC │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ YFQSMPQHL ┆ ATCATCAC │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ QCP…      ┆ CATCAT…  │
│ SGC_S_014 ┆ SGC_S_014 ┆ SGC_S_014 ┆ true      ┆ … ┆ SRCA-e001 ┆ 3         ┆ MHHHHHHHH ┆ ATGCACCA │
│ 987       ┆ 987       ┆ 987       ┆           ┆   ┆           ┆           ┆ HHDLGTENL ┆ TCATCATC │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ YFQSMIQAE ┆ ATCATCAC │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ EWY…      ┆ CATCAT…  │
│ SGC_S_014 ┆ SGC_S_014 ┆ SGC_S_014 ┆ true      ┆ … ┆ STAP1A-e0 ┆ 2         ┆ MHHHHHHHH ┆ ATGCACCA │
│ 988       ┆ 988       ┆ 988       ┆           ┆   ┆ 01        ┆           ┆ HHDLGTENL ┆ TCATCATC │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ YFQSMDYVD ┆ ATCATCAC │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ VLN…      ┆ CATCAT…  │
│ SGC_S_014 ┆ SGC_S_014 ┆ SGC_S_014 ┆ true      ┆ … ┆ STAP2A-e0 ┆ 2         ┆ MHHHHHHHH ┆ ATGCACCA │
│ 989       ┆ 989       ┆ 989       ┆           ┆   ┆ 01        ┆           ┆ HHDLGTENL ┆ TCATCATC │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ YFQSMALET ┆ ATCATCAC │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ PSC…      ┆ CATCAT…  │
│ SGC_S_014 ┆ SGC_S_014 ┆ SGC_S_014 ┆ true      ┆ … ┆ STAT1A-e0 ┆ 3         ┆ MHHHHHHHH ┆ ATGCACCA │
│ 990       ┆ 990       ┆ 990       ┆           ┆   ┆ 01        ┆           ┆ HHDLGTENL ┆ TCATCATC │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ YFQSMSTVM ┆ ATCATCAC │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ LDK…      ┆ CATCAT…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [7]:

def get_taxon_name(taxon_id: int) -> str | None:
    url = f"https://rest.uniprot.org/taxonomy/{taxon_id}.json"
    headers = {'User-Agent': 'Python code generated by Claude'}
    try:
        resp = session.get(url, headers=headers, timeout=15)
        resp.raise_for_status()
        data = resp.json()
        return data.get('scientificName')
    except Exception as e:
        print(f"Error fetching taxon {taxon_id}: {e}")
        return None

taxon_ids = df.select(pl.col.taxon_id.unique())['taxon_id'].to_list()
taxon_id_to_name = {tid: get_taxon_name(tid) for tid in taxon_ids}
taxon_id_to_name

{5664: 'Leishmania major',
 5694: 'Trypanosoma equiperdum',
 5702: 'Trypanosoma brucei brucei',
 5821: 'Plasmodium berghei',
 5843: 'Plasmodium falciparum (isolate NF54)',
 8364: 'Xenopus tropicalis',
 9430: 'Desmodus rotundus',
 9483: 'Callithrix jacchus',
 9515: 'Sapajus apella',
 9541: 'Macaca fascicularis',
 9544: 'Macaca mulatta',
 9595: 'Gorilla gorilla gorilla',
 9598: 'Pan troglodytes',
 9601: 'Pongo abelii',
 9606: 'Homo sapiens',
 9669: 'Mustela putorius furo',
 9685: 'Felis catus',
 9713: 'Leptonychotes weddellii',
 9796: 'Equus caballus',
 9913: 'Bos taurus',
 9986: 'Oryctolagus cuniculus',
 10029: 'Cricetulus griseus',
 10090: 'Mus musculus',
 11103: 'Hepacivirus hominis',
 30522: 'Bos indicus x Bos taurus',
 37293: 'Aotus nancymaae',
 51337: 'Jaculus jaculus',
 57439: 'Upupa epops',
 61853: 'Nomascus leucogenys',
 69293: 'Gasterosteus aculeatus',
 75743: 'Scyliorhinus torazame',
 77932: 'Diceros bicornis minor',
 113115: 'Rhinopomastus cyanomelas',
 126794: 'Vaccinia virus (strain Ankara)',
 127582: 'Trichechus manatus latirostris',
 137071: 'Plasmodium falciparum (isolate HB3)',
 185431: 'Trypanosoma brucei brucei (strain 927/4 GUTat10.1)',
 301447: 'Streptococcus pyogenes serotype M1',
 325343: 'Eurystomus gularis',
 432359: 'Toxoplasma gondii (strain ATCC 50861 / VEG)',
 508771: 'Toxoplasma gondii (strain ATCC 50611 / Me49)',
 679716: 'Trypanosoma brucei gambiense (strain MHOM/CI/86/DAL972)',
 1207470: 'Streptococcus pyogenes M1 476',
 2847144: 'hepatitis C virus genotype 1a'}

In [8]:
expert_metadata = pl.read_excel(
    '~/Documents/nicola_paper_2026/Supplementary Sheet S2_26052026.xlsx',
    sheet_name='E. coli', has_header=False, 
).transpose(column_names='column_1').select('ID', 'Description', 'Importance', 'What to capture')
expert_metadata

shape: (53, 4)
┌─────┬────────────────────────────────┬───────────────────────────┬───────────────────────────────┐
│ ID  ┆ Description                    ┆ Importance                ┆ What to capture               │
│ --- ┆ ---                            ┆ ---                       ┆ ---                           │
│ str ┆ str                            ┆ str                       ┆ str                           │
╞═════╪════════════════════════════════╪═══════════════════════════╪═══════════════════════════════╡
│ T1  ┆ Protein name  (designed const… ┆ Critical                  ┆ Protein name according to     │
│     ┆                                ┆                           ┆ UniP…                         │
│ T2  ┆ Gene name (HGNC)               ┆ Highly Enabling           ┆ Gene name according to HGNC   │
│     ┆                                ┆                           ┆ na…                           │
│ T3  ┆ Gene species (NCBI)            ┆ Optional                  ┆ Taxonomy according to NCBI    │
│     ┆                                ┆                           ┆ (e.…                          │
│ T4  ┆ UniProt ID                     ┆ Optional/ highly enabling ┆ UniProt identifier e.g.       │
│     ┆                                ┆                           ┆ P00918                        │
│ T5  ┆ Predicted protein              ┆ Highly Enabling           ┆ Intracellular,                │
│     ┆ localisation…                  ┆                           ┆ membrane-bound,…              │
│ …   ┆ …                              ┆ …                         ┆ …                             │
│ Q2  ┆ Final batch - aggregation      ┆ Highly Enabling           ┆ Monodisperse, broad,          │
│     ┆ stat…                          ┆                           ┆ multimeri…                    │
│ Q3  ┆ Final batch - stability /      ┆ Optional                  ┆ Thermal unfolding as assessed │
│     ┆ ther…                          ┆                           ┆ …                             │
│ Q4  ┆ Final batch - identity and-or  ┆ Highly Enabling           ┆ Has size of protein been      │
│     ┆ …                              ┆                           ┆ confi…                        │
│ O1  ┆ Other comments                 ┆ Optional                  ┆ Any other information deemed  │
│     ┆                                ┆                           ┆ u…                            │
│ O2  ┆ Data record completeness score ┆ Highly Enabling           ┆ Score between 1 and 10, 1     │
│     ┆                                ┆                           ┆ bein…                         │
└─────┴────────────────────────────────┴───────────────────────────┴───────────────────────────────┘

In [9]:

def get_uniprot_data(uniprot_id: str) -> tuple[str, str | None]:
    """Fetch subcellular localization from UniProt REST API."""
    if not uniprot_id:
        return uniprot_id, None
    url = f"https://rest.uniprot.org/uniprotkb/{uniprot_id}.json"
    headers = {'User-Agent': 'Python/generated by Claude'}
    try:
        resp = session.get(url, headers=headers, timeout=15)
        resp.raise_for_status()
        data = resp.json()
        uniprot_kb_id = data['uniProtkbId']
        locations = [
            subloc.get('location', {}).get('value')
            for comment in data.get('comments', [])
            if comment.get('commentType') == 'SUBCELLULAR LOCATION'
            for subloc in comment.get('subcellularLocations', [])
        ]
        locations = [l for l in locations if l]
        return uniprot_id, uniprot_kb_id, '; '.join(sorted(set(locations))) if locations else None
    except Exception as e:
        print(f"Error fetching {uniprot_id}: {e}")
        return uniprot_id, None

if uniprot_localisation_df_file.is_file():
    print(f"Reading uniprot df from {uniprot_localisation_df_file}")
    uniprot_df = pl.read_parquet(uniprot_localisation_df_file)
else:
    print(f"Loading uniprot df from the REST API")
    uniprot_ids = df.select(pl.col.uniprot_id.unique())['uniprot_id'].to_list()
    uniprot_data = []
    for uid in uniprot_ids:
        _, uniprot_kb_id, loc = get_uniprot_data(uid)
        uniprot_data.append((uid, uniprot_kb_id, loc))
        print(f"{uid}: {uniprot_kb_id}, {loc}")
    uniprot_df = pl.DataFrame(uniprot_data, schema={'uniprot_id': pl.String(), 'uniprot_name': pl.String(), 'localisation': pl.String()}, orient='row')
    uniprot_df.write_parquet(uniprot_localisation_df_file)

Loading uniprot df from the REST API
P41218: MNDA_HUMAN, Cytoplasm; Nucleus
Q9UBK8: MTRR_HUMAN, Cytoplasm
Q9H497: TOR3A_HUMAN, Cytoplasm; Endoplasmic reticulum lumen
Q00994: BEX3_HUMAN, Cytoplasm, cytosol; Nucleus
Q86YJ6: THNS2_HUMAN, Secreted
O14512: SOCS7_HUMAN, Cell membrane; Cytoplasm; Nucleus
Q8N1C8: Q8N1C8_HUMAN, None
Q9NWZ3: IRAK4_HUMAN, Cytoplasm
P09769: FGR_HUMAN, Cell membrane; Cell projection, ruffle membrane; Cytoplasm, cytoskeleton; Cytoplasm, cytosol; Mitochondrion inner membrane; Mitochondrion intermembrane space
O15523: DDX3Y_HUMAN, Cytoplasm; Nucleus
P27986: P85A_HUMAN, Cytoplasm
Q6PL18: ATAD2_HUMAN, Nucleus
Q92835: SHIP1_HUMAN, Cell membrane; Cytoplasm; Cytoplasm, cytoskeleton; Membrane; Membrane raft
Q9NRJ4: TULP4_HUMAN, Cytoplasm
O00154: BACH_HUMAN, Cytoplasm, cytosol; Mitochondrion
Q9BUB4: ADAT1_HUMAN, None
Q9UM47: NOTC3_HUMAN, Cell membrane; Nucleus
Q9NUL7: DDX28_HUMAN, Mitochondrion; Mitochondrion matrix; Mitochondrion matrix, mitochondrion nucleoid; Nucleus
B4DI54: B4DI54_HUMAN, None
Q9Y617: SERC_HUMAN, None
Q8WUH2: TGFA1_HUMAN, Cytoplasm; Early endosome
P53370: NUDT6_HUMAN, Cytoplasm; Mitochondrion; Nucleus
Q71V34: Q71V34_HUMAN, None
Q96QB1: RHG07_HUMAN, Cell junction, focal adhesion; Cytoplasm; Membrane
Q9Y600: CSAD_HUMAN, None
Q9BR76: COR1B_HUMAN, Cytoplasm, cytoskeleton; Cytoplasm, cytoskeleton, stress fiber
Q59FM7: Q59FM7_HUMAN, Chromosome; Nucleus
Q9H329: E41LB_HUMAN, Cell junction, tight junction; Cytoplasm
Q9NSY2: STAR5_HUMAN, None
W7K8U1: W7K8U1_PLAFO, None
Q59EN6: Q59EN6_HUMAN, Lipid droplet; Lysosome; Secreted, extracellular space
P38571: LICH_HUMAN, Lysosome
Q7Z4S9: SH2D6_HUMAN, None
P49441: INPP_HUMAN, None
Q6NTF7: ABC3H_HUMAN, Cytoplasm; Cytoplasm, P-body; Nucleus
O60678: ANM3_HUMAN, Cytoplasm, cytosol; Nucleus
P07148: FABPL_HUMAN, Cytoplasm
Q8N4L2: PP4P2_HUMAN, Cell membrane; Cytoplasmic vesicle, phagosome membrane; Late endosome membrane; Lysosome membrane
A0A024RDR3: A0A024RDR3_HUMAN, None
P31146: COR1A_HUMAN, Cytoplasm, cell cortex; Cytoplasm, cytoskeleton; Cytoplasmic vesicle, phagosome membrane
O60674: JAK2_HUMAN, Cytoplasm; Endomembrane system; Nucleus
B3KMW4: B3KMW4_HUMAN, Cytoplasmic vesicle, phagosome membrane; Early endosome membrane
Q16630: CPSF6_HUMAN, Cytoplasm; Nucleus; Nucleus speckle; Nucleus, nucleoplasm
Q9NRG1: PRDC1_HUMAN, None
Q9HC16: ABC3G_HUMAN, Cytoplasm; Cytoplasm, P-body; Nucleus
Q9H4Q4: PRD12_HUMAN, Nucleus
O15455: TLR3_HUMAN, Early endosome; Endoplasmic reticulum membrane; Endosome membrane
Q16548: B2LA1_HUMAN, Cytoplasm
Q3I5F7: ACOT6_HUMAN, Cytoplasm; Peroxisome
O95861: BPNT1_HUMAN, None
Q9NXH8: TOR4A_HUMAN, Membrane
B4DQC6: B4DQC6_HUMAN, None
O75747: P3C2G_HUMAN, Membrane
Q13508: NAR3_HUMAN, Cell membrane
O00622: CCN1_HUMAN, Secreted
Q504W7: Q504W7_HUMAN, Cell projection, cilium, photoreceptor outer segment; Cytoplasmic vesicle, phagosome membrane; Early endosome membrane; Golgi apparatus, trans-Golgi network; Membrane, clathrin-coated pit
Q07820: MCL1_HUMAN, Cytoplasm; Membrane; Mitochondrion; Nucleus, nucleoplasm
A0A024R684: A0A024R684_HUMAN, None
Q68CY7: Q68CY7_HUMAN, None
H2QYE6: H2QYE6_PANTR, Mitochondrion
Q9NQZ5: STAR7_HUMAN, Cytoplasm, cytosol; Mitochondrion intermembrane space; Mitochondrion outer membrane
Q8NCE0: SEN2_HUMAN, Nucleus; Nucleus, nucleolus
Q6UVY6: MOXD1_HUMAN, Endoplasmic reticulum membrane
Q13057: COASY_HUMAN, Cytoplasm, cytosol; Mitochondrion matrix
Q9NXN4: GDAP2_HUMAN, None
P16333: NCK1_HUMAN, Cytoplasm; Endoplasmic reticulum; Nucleus
G3QMH0: G3QMH0_GORGO, None
O60256: KPRB_HUMAN, None
Q96AC1: FERM2_HUMAN, Cell junction, focal adhesion; Cell projection, lamellipodium membrane; Cell surface; Cytoplasm; Cytoplasm, cell cortex; Cytoplasm, cytoskeleton; Cytoplasm, cytoskeleton, stress fiber; Cytoplasm, myofibril, sarcomere, I band; Membrane; Nucleus
O15056: SYNJ2_HUMAN, Cell membrane; Cell projection, ruffle membrane; Cytoplasm; Cytoplasm, cytoskeleton; Presynapse
Q13191: CBLB_HUMAN, Cytoplasm
Q53GJ1: Q53GJ1_HUMAN, Nucleus
P09917: LOX5_HUMAN, Cytoplasm; Cytoplasm, cytosol; Cytoplasm, perinuclear region; Nucleus envelope; Nucleus intermembrane space; Nucleus matrix; Nucleus membrane
P45973: CBX5_HUMAN, Chromosome; Chromosome, centromere; Nucleus
Q8IV08: PLD3_HUMAN, Early endosome membrane; Endoplasmic reticulum membrane; Endosome membrane; Golgi apparatus membrane; Late endosome membrane; Lysosome lumen
K7D5W5: K7D5W5_PANTR, Preautophagosomal structure membrane
Q9BW62: KATL1_HUMAN, Cytoplasm; Cytoplasm, cytoskeleton; Cytoplasm, cytoskeleton, spindle; Cytoplasm, cytoskeleton, spindle pole
P60842: IF4A1_HUMAN, Cell membrane; Cytoplasm, Stress granule; Cytoplasm, perinuclear region
Q13882: PTK6_HUMAN, Cell projection, ruffle; Cytoplasm; Membrane; Nucleus
O43143: DHX15_HUMAN, Nucleus; Nucleus, nucleolus
Q5TGL8: PXDC1_HUMAN, None
P46108: CRK_HUMAN, Cell membrane; Cytoplasm
Q96ES7: SGF29_HUMAN, Nucleus
P09874: PARP1_HUMAN, Chromosome; Cytoplasm; Cytoplasm, cytosol; Nucleus; Nucleus, nucleolus
Q96JC1: VPS39_HUMAN, Cytoplasm; Late endosome membrane; Lysosome membrane
B1AKJ6: B1AKJ6_HUMAN, Golgi apparatus, trans-Golgi network membrane; Late endosome membrane
J7M8R4: J7M8R4_STRP1, None
P38646: HSPA9_HUMAN, Cytoplasm; Mitochondrion; Mitochondrion matrix; Nucleus, nucleolus
E7ESY0: E7ESY0_HUMAN, None
Q9NR30: DDX21_HUMAN, Cytoplasm, cytosol; Mitochondrion; Nucleus, nucleolus; Nucleus, nucleoplasm
Q8IU60: DCP2_HUMAN, Cytoplasm, P-body; Nucleus
P27987: IP3KB_HUMAN, Cytoplasm; Cytoplasm, cytoskeleton; Endoplasmic reticulum
Q5T1C6: THEM4_HUMAN, Cell membrane; Cell projection, ruffle membrane; Cytoplasm; Mitochondrion; Mitochondrion inner membrane; Mitochondrion intermembrane space
Q96SU4: OSBL9_HUMAN, Endoplasmic reticulum-Golgi intermediate compartment membrane; Golgi apparatus, trans-Golgi network membrane; Late endosome membrane
Q59EJ8: Q59EJ8_HUMAN, Chromosome, centromere, kinetochore; Cytoplasm, cytoskeleton, spindle pole; Nucleus
Q96Q04: LMTK3_HUMAN, Cell projection, axon; Cell projection, dendrite; Golgi apparatus membrane; Membrane
P38919: IF4A3_HUMAN, Cytoplasm; Nucleus; Nucleus speckle
Q6ZVK8: NUD18_HUMAN, None
Q9Y697: NFS1_HUMAN, Cytoplasm, cytoskeleton, microtubule organizing center, centrosome; Cytoplasm, cytosol; Mitochondrion; Nucleus
O15054: KDM6B_HUMAN, Nucleus
P04629: NTRK1_HUMAN, Cell membrane; Early endosome membrane; Late endosome membrane; Recycling endosome membrane
Q6ZMQ8: LMTK1_HUMAN, Cytoplasm; Cytoplasm, perinuclear region; Membrane
Q9UHH9: IP6K2_HUMAN, Nucleus
Q9HA47: UCK1_HUMAN, None
A0A2I3SPT4: A0A2I3SPT4_PANTR, Cell membrane; Cytoplasm; Early endosome; Recycling endosome
O95931: CBX7_HUMAN, Nucleus
Q9UKK9: NUDT5_HUMAN, Nucleus
Q7M4L6: SHF_HUMAN, None
A1L4G7: A1L4G7_HUMAN, None
Q8WYH8: ING5_HUMAN, Chromosome; Nucleus
Q9H6Q3: SLAP2_HUMAN, Cell membrane; Cytoplasm; Cytoplasmic vesicle
Q07075: AMPE_HUMAN, Cell membrane
O43927: CXL13_HUMAN, Secreted
Q9Y6R0: NUMBL_HUMAN, Cytoplasm
Q7Z419: R144B_HUMAN, Cytoplasm; Mitochondrion membrane
O14986: PI51B_HUMAN, Cell membrane; Cytoplasm, cytosol; Endomembrane system
Q00005: 2ABB_HUMAN, Cytoplasm; Cytoplasm, cytoskeleton; Membrane; Mitochondrion; Mitochondrion outer membrane
O00294: TULP1_HUMAN, Cell membrane; Cytoplasm; Secreted; Synapse
Q16719: KYNU_HUMAN, Cytoplasm, cytosol
B7TQM3: B7TQM3_HUMAN, Cytoplasm
Q5W064: LIPJ_HUMAN, None
P16050: LOX15_HUMAN, Cell membrane; Cytoplasm, cytosol; Lipid droplet
Q16620: NTRK2_HUMAN, Cell membrane; Cell projection, axon; Cell projection, dendrite; Cytoplasm, perinuclear region; Early endosome membrane; Endosome membrane; Postsynaptic density
O15105: SMAD7_HUMAN, Cytoplasm; Nucleus
Q92529: SHC3_HUMAN, None
O14796: SH21B_HUMAN, None
Q99717: SMAD5_HUMAN, Cytoplasm; Mitochondrion; Nucleus
Q8N684: CPSF7_HUMAN, Cytoplasm; Nucleus
Q6YP21: KAT3_HUMAN, None
Q9BZ71: PITM3_HUMAN, Endomembrane system
P55157: MTP_HUMAN, Endoplasmic reticulum; Golgi apparatus
P17405: ASM_HUMAN, Lipid droplet; Lysosome; Secreted; Secreted, extracellular space
P23743: DGKA_HUMAN, Cytoplasm, cytosol
A0A024QZE9: A0A024QZE9_HUMAN, None
Q68CZ2: TENS3_HUMAN, Cell junction, focal adhesion; Cell projection, podosome
Q9Y2T3: GUAD_HUMAN, None
Q8TAT5: NEIL3_HUMAN, Chromosome; Nucleus
Q14847: LASP1_HUMAN, Cytoplasm, cell cortex; Cytoplasm, cytoskeleton
Q9BU89: DOHH_HUMAN, None
Q9BZF3: OSBL6_HUMAN, Cell membrane; Cytoplasm, cytosol; Endoplasmic reticulum membrane; Endosome membrane; Nucleus envelope
P11172: UMPS_HUMAN, None
P52757: CHIO_HUMAN, Membrane
Q9ELS8: Q9ELS8_9HEPC, Host cell membrane; Host cytoplasm, host perinuclear region; Host endoplasmic reticulum membrane; Host lipid droplet; Host mitochondrion membrane; Host nucleus; Virion membrane
Q6PFW1: VIP1_HUMAN, Cell membrane; Cytoplasm, cytosol
Q8NBU5: ATAD1_HUMAN, Mitochondrion outer membrane; Peroxisome membrane; Postsynaptic cell membrane
Q9H5N7: Q9H5N7_HUMAN, None
Q14765: STAT4_HUMAN, Cytoplasm; Nucleus
O75530: EED_HUMAN, Chromosome; Nucleus
P40763: STAT3_HUMAN, Cytoplasm; Nucleus
Q13393: PLD1_HUMAN, Cytoplasm, perinuclear region; Endoplasmic reticulum membrane; Golgi apparatus membrane; Late endosome membrane
Q9H2U1: DHX36_HUMAN, Cell projection, axon; Cell projection, dendrite; Chromosome, telomere; Cytoplasm; Cytoplasm, Stress granule; Cytoplasm, cytosol; Mitochondrion; Nucleus; Nucleus speckle; Perikaryon
Q9UJ14: GGT7_HUMAN, Membrane
Q6MZT2: Q6MZT2_HUMAN, Cell membrane
A0A0L7K967: A0A0L7K967_PLAFX, None
P24298: ALAT1_HUMAN, Cytoplasm
Q76ZX2: PG044_VACCA, Host cytoplasm
P22455: FGFR4_HUMAN, Cell membrane; Endoplasmic reticulum; Endosome; Secreted
Q7Z528: Q7Z528_HUMAN, Cell membrane; Endosome membrane; Golgi apparatus membrane; Membrane
G1SM82: G1SM82_RABIT, Cytoplasm
P16234: PGFRA_HUMAN, Cell membrane; Cell projection, cilium; Golgi apparatus
Q96GD3: SCMH1_HUMAN, Nucleus
Q14449: GRB14_HUMAN, Cytoplasm; Endosome membrane
O14543: SOCS3_HUMAN, None
B2R5S1: B2R5S1_HUMAN, Secreted
O43933: PEX1_HUMAN, Cytoplasm, cytosol; Peroxisome membrane
O15229: KMO_HUMAN, Mitochondrion outer membrane
P17643: TYRP1_HUMAN, Melanosome membrane
Q13485: SMAD4_HUMAN, Cytoplasm; Nucleus
Q8NCV1: ADAD2_HUMAN, Cytoplasm; Nucleus
P15498: VAV_HUMAN, None
Q9H2A7: CXL16_HUMAN, Cell membrane; Secreted
P18054: LOX12_HUMAN, Cytoplasm, cytosol; Membrane
Q4VB33: Q4VB33_HUMAN, Cytoplasm; Nucleus
Q59ES5: Q59ES5_HUMAN, Cytoplasmic vesicle membrane
P42356: PI4KA_HUMAN, Cell membrane; Cytoplasm
Q14781: CBX2_HUMAN, Chromosome; Nucleus
Q8NB90: AFG2A_HUMAN, Cytoplasm; Cytoplasm, cytoskeleton, spindle; Mitochondrion
Q9Y5P4: CERT_HUMAN, Cytoplasm; Endoplasmic reticulum; Golgi apparatus
P29376: LTK_HUMAN, Cell membrane
P78552: I13R1_HUMAN, Membrane
P61964: WDR5_HUMAN, Nucleus
A0A024R8L5: A0A024R8L5_HUMAN, None
Q9NR96: TLR9_HUMAN, Cytoplasmic vesicle, phagosome; Early endosome membrane; Endoplasmic reticulum membrane; Golgi apparatus membrane; Lysosome
Q9UIF7: MUTYH_HUMAN, Mitochondrion; Nucleus
Q96JH8: RADIL_HUMAN, None
B3UWV3: B3UWV3_PLABE, None
P52961: NAR1_HUMAN, Sarcoplasmic reticulum membrane
A8K0P2: A8K0P2_HUMAN, None
Q6P0N9: Q6P0N9_HUMAN, None
A0A1G4IBY4: A0A1G4IBY4_TRYEQ, Cytoplasm
O43187: IRAK2_HUMAN, None
O00198: HRK_HUMAN, Membrane; Mitochondrion
Q06203: PUR1_HUMAN, None
U3BSY6: U3BSY6_CALJA, None
Q9HB20: PKHA3_HUMAN, Golgi apparatus, trans-Golgi network membrane
Q57W26: ZC311_TRYB2, Cytoplasm
Q9BYX4: IFIH1_HUMAN, Cytoplasm; Mitochondrion; Nucleus
P32321: DCTD_HUMAN, None
O14862: AIM2_HUMAN, Cytoplasm; Inflammasome; Nucleus
Q9NZC3: GDE1_HUMAN, Cell membrane; Cytoplasmic vesicle membrane
P83916: CBX1_HUMAN, Nucleus
Q9Y3F4: STRAP_HUMAN, Cytoplasm; Nucleus
Q13239: SLAP1_HUMAN, Cytoplasm; Endosome
Q9UGN5: PARP2_HUMAN, Chromosome; Nucleus
P60891: PRPS1_HUMAN, None
Q9ULZ3: ASC_HUMAN, Cytoplasm; Endoplasmic reticulum; Golgi apparatus membrane; Inflammasome; Mitochondrion; Nucleus
P51532: SMCA4_HUMAN, Nucleus
O00459: P85B_HUMAN, None
Q4VCS5: AMOT_HUMAN, Cell junction, tight junction
Q92793: CBP_HUMAN, Cytoplasm; Nucleus
Q95Z61: Q95Z61_PLABE, None
O95786: RIGI_HUMAN, Cell junction, tight junction; Cell projection, ruffle membrane; Cytoplasm; Cytoplasm, cytoskeleton
Q9Y365: STA10_HUMAN, Cell projection, cilium, flagellum; Cytoplasm; Membrane
Q9NSW6: Q9NSW6_HUMAN, Cell projection, axon; Cell projection, dendrite; Cytoplasm, cytoskeleton, cilium basal body; Cytoplasm, cytoskeleton, microtubule organizing center, centrosome; Nucleus; Perikaryon
Q9NRA0: SPHK2_HUMAN, Cytoplasm; Endoplasmic reticulum; Lysosome membrane; Mitochondrion inner membrane; Nucleus
Q99259: DCE1_HUMAN, None
O94925: GLSK_HUMAN, Cytoplasm, cytosol; Mitochondrion; Mitochondrion matrix
O94953: KDM4B_HUMAN, Nucleus
P19113: DCHS_HUMAN, None
Q86UT6: NLRX1_HUMAN, Mitochondrion outer membrane
P17735: ATTY_HUMAN, None
K9IS34: K9IS34_DESRO, Cytoplasm
A0A8I5TCB3: A0A2J8UUK3_PONAB, Endoplasmic reticulum membrane; Golgi apparatus membrane
Q6B0I6: KDM4D_HUMAN, Nucleus
P22607: FGFR3_HUMAN, Cell membrane; Cytoplasmic vesicle; Endoplasmic reticulum; Secreted
P13385: TDGF1_HUMAN, Cell membrane; Secreted
P17980: PRS6A_HUMAN, Cytoplasm; Nucleus
Q5VUG0: SMBT2_HUMAN, Nucleus
Q96T88: UHRF1_HUMAN, Chromosome; Nucleus
Q13362: 2A5G_HUMAN, Chromosome, centromere; Nucleus
Q9Y2I7: FYV1_HUMAN, Cytoplasmic vesicle, phagosome membrane; Early endosome membrane; Endosome membrane; Late endosome membrane
G9KE96: G9KE96_MUSPF, Cytoplasm
Q9NV35: NUD15_HUMAN, None
A0A5F5XCU7: A0A5F5XCU7_FELCA, None
P31513: FMO3_HUMAN, Endoplasmic reticulum membrane; Microsome membrane
P22059: OSBP1_HUMAN, Cytoplasm, cytosol; Cytoplasm, perinuclear region; Endoplasmic reticulum membrane; Golgi apparatus membrane; Golgi apparatus, trans-Golgi network
O00142: KITM_HUMAN, Mitochondrion
A8K979: ERI2_HUMAN, None
Q9H0J9: PAR12_HUMAN, Cytoplasm, Stress granule; Golgi apparatus, trans-Golgi network; Nucleus
Q4GZ95: Q4GZ95_TRYB2, None
Q8WUK0: PTPM1_HUMAN, Mitochondrion inner membrane
P42338: PK3CB_HUMAN, Cytoplasm; Nucleus
P49915: GUAA_HUMAN, Cytoplasm, cytosol
Q07812: BAX_HUMAN, Cytoplasm; Mitochondrion outer membrane; Nucleus
Q14558: KPRA_HUMAN, None
A0A0F7UTT8: A0A0F7UTT8_TOXGV, None
Q9ULV8: CBLC_HUMAN, None
A0A7L1NM84: A0A7L1NM84_RHICY, Cytoplasm; Nucleus
Q9Y6T7: DGKB_HUMAN, Cell membrane; Cytoplasm; Postsynaptic cell membrane
A0A024RCD1: A0A024RCD1_HUMAN, None
Q8NFP7: NUD10_HUMAN, Cytoplasm
P43405: KSYK_HUMAN, Cell membrane; Cytoplasm, cytosol
B7Z5L6: B7Z5L6_HUMAN, Cytoplasm; Nucleus
Q07325: CXCL9_HUMAN, Secreted
Q5MNZ9: WIPI1_HUMAN, Cytoplasm, cytoskeleton; Cytoplasmic vesicle, clathrin-coated vesicle; Endosome; Golgi apparatus, trans-Golgi network; Preautophagosomal structure membrane
Q06190: P2R3A_HUMAN, None
B7Z3D4: B7Z3D4_HUMAN, Cell membrane; Cell projection, ruffle; Cytoplasm, cell cortex; Cytoplasm, cytoskeleton
P29350: PTN6_HUMAN, Cytoplasm; Nucleus
P35916: VGFR3_HUMAN, Cell membrane; Cytoplasm; Nucleus; Secreted
Q99570: PI3R4_HUMAN, Cytoplasmic vesicle, autophagosome; Late endosome; Membrane
Q9BXY8: BEX2_HUMAN, Cytoplasm; Nucleus
P43686: PRS6B_HUMAN, Cytoplasm; Nucleus
O75159: SOCS5_HUMAN, None
P17066: HSP76_HUMAN, None
Q9UBP0: SPAST_HUMAN, Cell projection, axon; Cytoplasm; Cytoplasm, cytoskeleton; Cytoplasm, cytoskeleton, microtubule organizing center, centrosome; Cytoplasm, cytoskeleton, spindle; Cytoplasm, perinuclear region; Endoplasmic reticulum; Endoplasmic reticulum membrane; Endosome; Lipid droplet; Membrane; Midbody; Nucleus; Nucleus membrane
A0A024R1K5: A0A024R1K5_HUMAN, None
Q9NWD9: BEX4_HUMAN, Cytoplasm; Cytoplasm, cytoskeleton, spindle pole; Nucleus
A0A2I0BXJ0: A0A2I0BXJ0_PLAFO, None
Q8N1F8: S11IP_HUMAN, Cytoplasm
Q7LG56: RIR2B_HUMAN, Cytoplasm; Nucleus
P42681: TXK_HUMAN, Cell membrane; Cytoplasm; Nucleus
Q15735: PI5PA_HUMAN, Cytoplasm
A0A2J8QEF8: A0A2J8QEF8_PANTR, None
O75943: RAD17_HUMAN, Chromosome; Nucleus
B7ZAG8: B7ZAG8_HUMAN, Cytoplasm; Endomembrane system
P27708: PYR1_HUMAN, Cytoplasm; Nucleus
Q9Y265: RUVB1_HUMAN, Cytoplasm; Cytoplasm, cytoskeleton, microtubule organizing center, centrosome; Dynein axonemal particle; Membrane; Nucleus matrix; Nucleus, nucleoplasm
Q92934: BAD_HUMAN, Cytoplasm; Mitochondrion outer membrane
Q13608: PEX6_HUMAN, Cell projection, cilium, photoreceptor outer segment; Cytoplasm, cytosol; Peroxisome membrane
P48775: T23O_HUMAN, None
A0A7L4D9V4: A0A7L4D9V4_9AVES, Cytoplasm; Nucleus
Q15172: 2A5A_HUMAN, Chromosome, centromere; Cytoplasm; Nucleus
O95271: TNKS1_HUMAN, Chromosome, telomere; Cytoplasm; Cytoplasm, cytoskeleton, microtubule organizing center, centrosome; Cytoplasm, cytoskeleton, spindle pole; Golgi apparatus membrane; Nucleus, nuclear pore complex
F7GPV9: F7GPV9_MACMU, None
Q9Y5X9: LIPG_HUMAN, Secreted
P48506: GSH1_HUMAN, None
P42858: HD_HUMAN, Cytoplasm; Cytoplasmic vesicle, autophagosome; Early endosome; Nucleus
Q9Y6F1: PARP3_HUMAN, Chromosome; Cytoplasm, cytoskeleton, microtubule organizing center, centrosome; Cytoplasm, cytoskeleton, microtubule organizing center, centrosome, centriole; Nucleus
P08243: ASNS_HUMAN, None
Q9Y5Y7: LYVE1_HUMAN, Cell membrane
Q4G134: Q4G134_HUMAN, None
O60880: SH21A_HUMAN, Cytoplasm
E9PEI2: E9PEI2_HUMAN, Nucleus
P13995: MTDC_HUMAN, Mitochondrion
Q06187: BTK_HUMAN, Cell membrane; Cytoplasm; Membrane raft; Nucleus
Q9UNW1: MINP1_HUMAN, Cell membrane; Endoplasmic reticulum lumen; Secreted
Q9Y616: IRAK3_HUMAN, Cytoplasm; Nucleus
Q6DHV7: ADAL_HUMAN, Cytoplasm, cytosol
B3KN09: B3KN09_HUMAN, Mitochondrion inner membrane
P34931: HS71L_HUMAN, None
O95361: TRI16_HUMAN, Cytoplasm
P22557: HEM0_HUMAN, Mitochondrion inner membrane
Q01973: ROR1_HUMAN, Cell membrane; Cell projection, axon
Q9NTJ5: SAC1_HUMAN, Endoplasmic reticulum membrane; Golgi apparatus membrane
Q9UGK3: STAP2_HUMAN, Cytoplasm
Q16760: DGKD_HUMAN, Cell membrane; Cytoplasm; Membrane, clathrin-coated pit
Q8WXI4: ACO11_HUMAN, Cytoplasm; Mitochondrion matrix
Q16739: CEGT_HUMAN, Golgi apparatus membrane
Q69YP8: Q69YP8_HUMAN, Cell membrane; Cell projection, ruffle; Cytoplasm, cell cortex; Cytoplasm, cytoskeleton
Q6AI50: Q6AI50_HUMAN, Nucleus, nucleolus
P49753: ACOT2_HUMAN, Mitochondrion
Q9BQ39: DDX50_HUMAN, Cytoplasm; Nucleus, nucleolus
Q8WW27: ABEC4_HUMAN, None
Q13547: HDAC1_HUMAN, Nucleus
Q59F66: Q59F66_HUMAN, None
Q13075: BIRC1_HUMAN, None
P51451: BLK_HUMAN, Cell membrane
Q8NCT1: ARRD4_HUMAN, Cell membrane; Cytoplasmic vesicle; Early endosome
Q15173: 2A5B_HUMAN, Cytoplasm
Q13185: CBX3_HUMAN, Nucleus
O15067: PUR4_HUMAN, Cytoplasm
B7ZLE8: B7ZLE8_HUMAN, None
P52630: STAT2_HUMAN, Cytoplasm; Nucleus
Q9H1P3: OSBL2_HUMAN, Cell membrane; Cell projection, stereocilium; Cytoplasm, cytosol; Lipid droplet
Q9NPJ3: ACO13_HUMAN, Cytoplasm, cytoskeleton, spindle; Cytoplasm, cytosol; Mitochondrion; Nucleus
Q53FP3: Q53FP3_HUMAN, None
P06858: LIPL_HUMAN, Cell membrane; Secreted; Secreted, extracellular space, extracellular matrix
A0A2J8L082: A0A2J8L082_PANTR, None
O14544: SOCS6_HUMAN, None
Q8NHF4: Q8NHF4_CRIGR, Cytoplasm; Nucleus
P11021: BIP_HUMAN, Cell surface; Cytoplasm; Endoplasmic reticulum lumen; Melanosome
Q05CW7: Q05CW7_HUMAN, Nucleus, nucleolus
B4DKM2: B4DKM2_HUMAN, Cytoplasm
P52735: VAV2_HUMAN, None
Q9BTU6: P4K2A_HUMAN, Cell membrane; Cell projection, dendrite; Cell projection, neuron projection; Cytoplasmic vesicle; Endosome; Endosome membrane; Golgi apparatus, trans-Golgi network membrane; Membrane; Membrane raft; Mitochondrion; Perikaryon; Presynaptic cell membrane; Synapse, synaptosome
Q7Z4W0: Q7Z4W0_HUMAN, Nucleus
Q9NY59: NSMA2_HUMAN, Cell membrane; Golgi apparatus membrane
A7E2B6: A7E2B6_HUMAN, Nucleus
Q9Y2C9: TLR6_HUMAN, Cell membrane; Cytoplasmic vesicle, phagosome membrane; Golgi apparatus; Membrane raft
Q9NX62: IMPA3_HUMAN, Golgi apparatus; Golgi apparatus, trans-Golgi network membrane
A0A2R8Y7Z4: A0A2R8Y7Z4_HUMAN, Membrane
O15357: SHIP2_HUMAN, Basal cell membrane; Cell projection, filopodium; Cell projection, lamellipodium; Cytoplasm, cytoskeleton; Cytoplasm, cytoskeleton, spindle pole; Cytoplasm, cytosol; Membrane; Nucleus; Nucleus speckle

In [10]:
df_tags = (
    df.join(alignments_df, on='fasta_id', how='inner')
    .filter(~pl.col.subj_id.is_in(['<Start_M>', '<unaligned>', '<TEV>', '<SG_Link>', '<VDLG>', '<Thrombin>']))
    .group_by('id', 'subj_id')
    .agg(
        pl.col.uniprot_id.first(),
        pl.col.aln_subj_start.min(),
        pl.col.aln_subj_end.max(),
        pl.col.aln_start.min(),
        pl.col.ident_count.sum()
    )
    .sort('id', 'aln_start')
)
id_to_name = {}
name_components = []
current_id = ''
re_angles = re.compile('^<|>$')
for r in df_tags.rows(named=True):
    if r['id'] != current_id:
        if current_id != '':
            id_to_name[current_id] = '-'.join(name_components)
        name_components = []
        current_id = r['id']
    if r['subj_id'] == r['uniprot_id']:
        uniprot_name = uniprot_df.filter(uniprot_id=r['uniprot_id']).select('uniprot_name')[0,0]
        uniprot_name += f"[{r['aln_subj_start']+1}-{r['aln_subj_end']}]"
        name_components.append(uniprot_name)
    elif r['subj_id'] == '<His>':
        name_components.append(f"{r['ident_count']}xHis")
    elif r['subj_id'] == '<6His-link2>':
        name_components.append(f"6xHis")
    else:
        name_components.append(re_angles.sub('', r['subj_id']))

id_to_name[current_id] = '-'.join(name_components)

In [11]:
sgc_stockholm_expert_raw=pl.DataFrame({
    # 'id': df['id'],
    'T1': df['id'].replace_strict(id_to_name),
    'T2': df['gene_id'],
    'T3': df['taxon_id'].replace_strict(taxon_id_to_name),
    'T4': df['uniprot_id'],
    'C1': df['dna_seq'],
    'C2': df['protein_seq'],
    'C5': df['vector_seq'],
    'P7': df['yield_cat'].replace_strict({
        0: 'none',
        1: 'low',
        2: 'medium',
        3: 'high',
        4: 'very high'
    }),
    'P4': df['yield_binary'].cast(pl.String)
}).with_columns(
    C4=pl.lit('pNIC28-Bsa4'),
    E1=pl.lit('BL21-Gold(DE3) (Stratagene)'),
    E2=pl.lit('Terrific Broth (TB) (Formedium) + 50 μg/mL kanamycin + 34 μg/mL chloramphenicol'),
    E3=pl.lit('1 ml'),
    E4=pl.lit('18°C'),
    E5=pl.lit('pRARE2 plasmid from the Rosetta2 strain (Novagen)'),
    E6=pl.lit('700 rpm, 70 vertical pulses per minute in a small radius shaker (Glas-Col Vertiga)'),
    E7=pl.lit('96-well square deep-well plates (ABgene), well volume = 2.2 mL'),
    E8=pl.lit('overnight'),
    EB1=pl.lit('37°C'),
    EB2=pl.lit('2'),
    EB3=pl.lit('IPTG 0.5mM'),
    E10=pl.lit('detergents and freeze-thaw'),
    E11=pl.lit('pH 8.0; BUFF HEPES 100mM; '
               'SALT NaCl, 500mM; '
               'GLY 10%; '
               'RED TCEP, 0.5mM; '
               'OTHER imidazole, 10mM; '
               'OTHER lysozyme from chicken egg-white (Fluka), 1 mg/mL; '
               'OTHER Roche Complete EDTA-free protease inhibitor cocktail, 1 tablet/100 mL; '
               'OTHER n-dodecyl β-d-maltoside (DDM), 0.1%; '
               'OTHER MgSO4, 1mM; '
               'OTHER Merk benzonase, 125 U/mL'),
    P6=pl.lit('Manual estimation based on relative SDS-PAGE band thickness'),
    P1=pl.lit('Ni-NTA IMAC'),
    P2=pl.lit('pH 7.5; BUFF HEPES 20mM; '
              'SALT NaCl, 500mM; '
              'GLY 10%; '
              'OTHER imidazole, 500mM; '
              'RED TCEP, 0.5mM; '),
    P3=pl.lit('Manual estimation based on relative SDS-PAGE band thickness'),
    O1=pl.lit("""
{
    'cell_line_link_addgene':'https://www.addgene.org/26242/', 
    'vector_link_genebank': 'https://www.ncbi.nlm.nih.gov/nuccore/EF198106.1',
    'vector_link_addgene': 'https://www.addgene.org/26103/',
    'publication_doi' : '10.1016/j.pep.2007.11.008'
}
"""),
    O2=pl.lit('7')
).join(
    uniprot_df, left_on='T4', right_on='uniprot_id', how='inner', coalesce=True
).rename({'localisation': 'T5'})

In [12]:
sgc_stockholm_expert = pl.concat([
    expert_metadata.transpose(column_names='ID'), 
    sgc_stockholm_expert_raw
], how='diagonal').select(expert_metadata['ID'].to_list())
sgc_stockholm_expert

shape: (14_679, 53)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ T1        ┆ T2        ┆ T3        ┆ T4        ┆ … ┆ Q3        ┆ Q4        ┆ O1        ┆ O2       │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Protein   ┆ Gene name ┆ Gene      ┆ UniProt   ┆ … ┆ Final     ┆ Final     ┆ Other     ┆ Data     │
│ name      ┆ (HGNC)    ┆ species   ┆ ID        ┆   ┆ batch -   ┆ batch -   ┆ comments  ┆ record   │
│ (designed ┆           ┆ (NCBI)    ┆           ┆   ┆ stability ┆ identity  ┆           ┆ complete │
│ const…    ┆           ┆           ┆           ┆   ┆ / ther…   ┆ and-or …  ┆           ┆ ness     │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ score    │
│ Critical  ┆ Highly    ┆ Optional  ┆ Optional/ ┆ … ┆ Optional  ┆ Highly    ┆ Optional  ┆ Highly   │
│           ┆ Enabling  ┆           ┆ highly    ┆   ┆           ┆ Enabling  ┆           ┆ Enabling │
│           ┆           ┆           ┆ enabling  ┆   ┆           ┆           ┆           ┆          │
│ Protein   ┆ Gene name ┆ Taxonomy  ┆ UniProt   ┆ … ┆ Thermal   ┆ Has size  ┆ Any other ┆ Score    │
│ name      ┆ according ┆ according ┆ identifie ┆   ┆ unfolding ┆ of        ┆ informati ┆ between  │
│ according ┆ to HGNC   ┆ to NCBI   ┆ r e.g.    ┆   ┆ as        ┆ protein   ┆ on deemed ┆ 1 and    │
│ to UniP…  ┆ na…       ┆ (e.…      ┆ P00918    ┆   ┆ assessed  ┆ been      ┆ u…        ┆ 10, 1    │
│           ┆           ┆           ┆           ┆   ┆ …         ┆ confi…    ┆           ┆ bein…    │
│ 6xHis-ARR ┆ ARR3      ┆ Homo      ┆ P36575    ┆ … ┆ null      ┆ null      ┆           ┆ 7        │
│ C_HUMAN[3 ┆           ┆ sapiens   ┆           ┆   ┆           ┆           ┆ {         ┆          │
│ -356]     ┆           ┆           ┆           ┆   ┆           ┆           ┆ 'cell_lin ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ e_link_ad ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ dgene…    ┆          │
│ 6xHis-ARR ┆ ARR3      ┆ Homo      ┆ P36575    ┆ … ┆ null      ┆ null      ┆           ┆ 7        │
│ C_HUMAN[3 ┆           ┆ sapiens   ┆           ┆   ┆           ┆           ┆ {         ┆          │
│ -359]     ┆           ┆           ┆           ┆   ┆           ┆           ┆ 'cell_lin ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ e_link_ad ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ dgene…    ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 10xHis-SO ┆ SOCS7     ┆ Homo      ┆ O14512    ┆ … ┆ null      ┆ null      ┆           ┆ 7        │
│ CS7_HUMAN ┆           ┆ sapiens   ┆           ┆   ┆           ┆           ┆ {         ┆          │
│ [373-530] ┆           ┆           ┆           ┆   ┆           ┆           ┆ 'cell_lin ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ e_link_ad ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ dgene…    ┆          │
│ 10xHis-SR ┆ SRC       ┆ Homo      ┆ P12931    ┆ … ┆ null      ┆ null      ┆           ┆ 7        │
│ C_HUMAN[1 ┆           ┆ sapiens   ┆           ┆   ┆           ┆           ┆ {         ┆          │
│ 46-250]   ┆           ┆           ┆           ┆   ┆           ┆           ┆ 'cell_lin ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ e_link_ad ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ dgene…    ┆          │
│ 10xHis-ST ┆ STAP1     ┆ Homo      ┆ Q9ULZ2    ┆ … ┆ null      ┆ null      ┆           ┆ 7        │
│ AP1_HUMAN ┆           ┆ sapiens   ┆           ┆   ┆           ┆           ┆ {         ┆          │
│ [167-285] ┆           ┆           ┆           ┆   ┆           ┆           ┆ 'cell_lin ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ e_link_ad ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ dgene…    ┆          │
│ 10xHis-ST ┆ STAP2     ┆ Homo      ┆ Q9UGK3    ┆ … ┆ null      ┆ null      ┆           ┆ 7        │
│ AP2_HUMAN ┆           ┆ sapiens   ┆           ┆   ┆           ┆           ┆ {         ┆          │
│ [147-269] ┆           ┆           ┆           ┆   ┆           ┆           ┆ 'cell_lin ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ e_link_ad ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ dgene…    ┆          │
│ 10xHis-ST ┆ STAT1     ┆ Homo      ┆ P42224    ┆ … ┆ null      ┆ null      ┆           ┆ 7        │
│ AT1_HUMAN ┆           ┆ sapiens   ┆           ┆   ┆           ┆           ┆ {         ┆          │
│ [132-713] ┆           ┆           ┆           ┆   ┆           ┆           ┆ 'cell_lin ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ e_link_ad ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ dgene…    ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [13]:

def resolve(filename) -> pathlib.Path:
    if type(filename) == str:
        filename = pathlib.Path(filename)
    if str(filename).startswith('~'):
        filename = filename.expanduser()
    return filename.resolve()

def write_fasta(sequences:typing.Iterable[typing.Tuple[str, str]]|typing.Mapping[str, str], filename:str|os.PathLike, seq_chunk_size:int=80):
    """
    Write a sequence of (id, sequence) tuples to a FASTA file.
    :param sequences: A sequence of (id, sequence) tuples.
    :param filename: The name of the file to write to.
    :param seq_chunk_size: The size of each sequence chunk in the output file.
    """
    if isinstance(sequences, typing.Mapping):
        sequences = sequences.items()
    filename = resolve(filename)
    is_gzip = filename.suffix == '.gz'
    with gzip.open(filename, 'wt') if is_gzip else open(filename, 'w') as f:
        for seq_id, sequence in sequences:
            f.write(f">{seq_id}\n")
            for i in range(0, len(sequence), seq_chunk_size):
                f.write(sequence[i:i + seq_chunk_size] + '\n')

In [14]:
# sgc_stockholm_expert.write_excel('~/Documents/nicola_paper_2026/sgc_stockholm_expert.xlsx')

In [15]:
sgc_stockholm_expert_raw.select(pl.col.C1.n_unique())

shape: (1, 1)
┌───────┐
│ C1    │
│ ---   │
│ u32   │
╞═══════╡
│ 11023 │
└───────┘

In [16]:
sgc_stockholm_expert_raw.shape

(14676, 31)

In [17]:
assert sgc_stockholm_expert_raw.group_by('C2').agg(pl.col.T1.n_unique()).max().select('T1').item() == 1
fasta_df = (
    sgc_stockholm_expert_raw.with_row_index("row_idx")
    .group_by('C2')
    .agg(fasta_id=pl.col.T1.first() + pl.lit('-') + (pl.col.row_idx.first() + 1).cast(pl.String))
)
write_fasta(zip(fasta_df['fasta_id'], fasta_df['C2']), 
            '/Users/evgeny/Documents/nicola_paper_2026/biostudies/sgc_stockholm_expert.fasta.gz')